linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - megacheck # already covered by other linters.
    - gosec
